// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP_Ticket_ReSell_DAO.Models;

public partial class Image
{
    public int ID_Image { get; set; }

    public string Image_URL { get; set; }

    public int? ID_Ticket { get; set; }

    public virtual Ticket ID_TicketNavigation { get; set; }
}