// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP_Ticket_ReSell_DAO.Models;

public partial class Payment
{
    public int ID_Payment { get; set; }

    public string Name { get; set; }

    public string Payment_Provider { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}