e// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SWP_Ticket_ReSell_DAO.Models;

public partial class swp1Context : DbContext
{
    public swp1Context(DbContextOptions<swp1Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Boxchat> Boxchats { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Feedback> Feedbacks { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderDetail> OrderDetails { get; set; }

    public virtual DbSet<Package> Packages { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Report> Reports { get; set; }

    public virtual DbSet<Request> Requests { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Ticket> Tickets { get; set; }

    public virtual DbSet<Transaction> Transactions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Boxchat>(entity =>
        {
            entity.HasKey(e => e.ID_Boxchat).HasName("PK__Boxchat__23A1BC06BAECE8AF");

            entity.ToTable("Boxchat");

            entity.Property(e => e.Chat_content).HasColumnType("text");

            entity.HasOne(d => d.Buyer).WithMany(p => p.BoxchatBuyers)
                .HasForeignKey(d => d.Buyer_ID)
                .HasConstraintName("FK__Boxchat__Buyer_I__5CD6CB2B");

            entity.HasOne(d => d.ID_TicketNavigation).WithMany(p => p.Boxchats)
                .HasForeignKey(d => d.ID_Ticket)
                .HasConstraintName("FK__Boxchat__ID_Tick__5AEE82B9");

            entity.HasOne(d => d.Seller).WithMany(p => p.BoxchatSellers)
                .HasForeignKey(d => d.Seller_ID)
                .HasConstraintName("FK__Boxchat__Seller___5BE2A6F2");
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.ID_Customer).HasName("PK__Customer__2D8FDE5F44AE6D5B");

            entity.ToTable("Customer");

            entity.Property(e => e.Avatar).IsUnicode(false);
            entity.Property(e => e.Average_feedback).HasColumnType("decimal(3, 2)");
            entity.Property(e => e.Contact)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Email)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Package_expiration_date).HasColumnType("datetime");
            entity.Property(e => e.Package_registration_time).HasColumnType("datetime");
            entity.Property(e => e.Password)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_PackageNavigation).WithMany(p => p.Customers)
                .HasForeignKey(d => d.ID_Package)
                .HasConstraintName("FK__Customer__ID_Pac__4E88ABD4");

            entity.HasOne(d => d.ID_RoleNavigation).WithMany(p => p.Customers)
                .HasForeignKey(d => d.ID_Role)
                .HasConstraintName("FK__Customer__ID_Rol__4D94879B");
        });

        modelBuilder.Entity<Feedback>(entity =>
        {
            entity.HasKey(e => e.ID_Feedback).HasName("PK__Feedback__7CA05C3FFF2F0542");

            entity.ToTable("Feedback");

            entity.Property(e => e.Comment).HasColumnType("text");
            entity.Property(e => e.History).HasColumnType("datetime");

            entity.HasOne(d => d.ID_OrderNavigation).WithMany(p => p.Feedbacks)
                .HasForeignKey(d => d.ID_Order)
                .HasConstraintName("FK__Feedback__ID_Ord__66603565");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.ID_Notification).HasName("PK__Notifica__09D4F1665264D901");

            entity.ToTable("Notification");

            entity.Property(e => e.Event)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Organizing_time).HasColumnType("datetime");
            entity.Property(e => e.Title)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_TicketNavigation).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.ID_Ticket)
                .HasConstraintName("FK__Notificat__ID_Ti__693CA210");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.ID_Order).HasName("PK__Order__EC9FA9557AE3E3F9");

            entity.ToTable("Order");

            entity.Property(e => e.Create_At).HasColumnType("datetime");
            entity.Property(e => e.Payment_method)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Shipping_time).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_CustomerNavigation).WithMany(p => p.Orders)
                .HasForeignKey(d => d.ID_Customer)
                .HasConstraintName("FK__Order__ID_Custom__5441852A");
        });

        modelBuilder.Entity<OrderDetail>(entity =>
        {
            entity.HasKey(e => e.ID_OrderDetail).HasName("PK__OrderDet__855D4EF57A4371E0");

            entity.ToTable("OrderDetail");

            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Total_price).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.ID_OrderNavigation).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.ID_Order)
                .HasConstraintName("FK__OrderDeta__ID_Or__571DF1D5");

            entity.HasOne(d => d.ID_TicketNavigation).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.ID_Ticket)
                .HasConstraintName("FK__OrderDeta__ID_Ti__5812160E");
        });

        modelBuilder.Entity<Package>(entity =>
        {
            entity.HasKey(e => e.ID_Package).HasName("PK__Package__10A648729634C48B");

            entity.ToTable("Package");

            entity.Property(e => e.Description).IsUnicode(false);
            entity.Property(e => e.Name_Package)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.ID_Payment).HasName("PK__Payment__C2118ADE482804F8");

            entity.ToTable("Payment");

            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Payment_Provider)
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Report>(entity =>
        {
            entity.HasKey(e => e.ID_Report).HasName("PK__Report__C6245294A3ED8C52");

            entity.ToTable("Report");

            entity.Property(e => e.Comment).HasColumnType("text");
            entity.Property(e => e.History).HasColumnType("datetime");

            entity.HasOne(d => d.ID_CustomerNavigation).WithMany(p => p.Reports)
                .HasForeignKey(d => d.ID_Customer)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Report__ID_Custo__6C190EBB");

            entity.HasOne(d => d.ID_OrderNavigation).WithMany(p => p.Reports)
                .HasForeignKey(d => d.ID_Order)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Report__ID_Order__6D0D32F4");
        });

        modelBuilder.Entity<Request>(entity =>
        {
            entity.HasKey(e => e.ID_Request).HasName("PK__Request__D5509880A41F2AC1");

            entity.ToTable("Request");

            entity.Property(e => e.History).HasColumnType("datetime");
            entity.Property(e => e.Price_want).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.ID_CustomerNavigation).WithMany(p => p.Requests)
                .HasForeignKey(d => d.ID_Customer)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Request__ID_Cust__70DDC3D8");

            entity.HasOne(d => d.ID_TicketNavigation).WithMany(p => p.Requests)
                .HasForeignKey(d => d.ID_Ticket)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Request__ID_Tick__6FE99F9F");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.ID_Role).HasName("PK__Role__43DCD32D4454F823");

            entity.ToTable("Role");

            entity.Property(e => e.Name_role)
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Ticket>(entity =>
        {
            entity.HasKey(e => e.ID_Ticket).HasName("PK__Ticket__79F5DC08E5679D45");

            entity.ToTable("Ticket");

            entity.Property(e => e.Description).HasColumnType("text");
            entity.Property(e => e.Event_Date).HasColumnType("datetime");
            entity.Property(e => e.Image).IsUnicode(false);
            entity.Property(e => e.Location)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Show_Name)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Ticket_History).HasColumnType("datetime");
            entity.Property(e => e.Ticket_category)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_CustomerNavigation).WithMany(p => p.Tickets)
                .HasForeignKey(d => d.ID_Customer)
                .HasConstraintName("FK__Ticket__ID_Custo__5165187F");
        });

        modelBuilder.Entity<Transaction>(entity =>
        {
            entity.HasKey(e => e.ID_Transaction).HasName("PK__Transact__3F16C92D092CD97A");

            entity.ToTable("Transaction");

            entity.Property(e => e.Created_At).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_CustomerNavigation).WithMany(p => p.Transactions)
                .HasForeignKey(d => d.ID_Customer)
                .HasConstraintName("FK__Transacti__ID_Cu__628FA481");

            entity.HasOne(d => d.ID_OrderNavigation).WithMany(p => p.Transactions)
                .HasForeignKey(d => d.ID_Order)
                .HasConstraintName("FK__Transacti__ID_Or__619B8048");

            entity.HasOne(d => d.ID_PaymentNavigation).WithMany(p => p.Transactions)
                .HasForeignKey(d => d.ID_Payment)
                .HasConstraintName("FK__Transacti__ID_Pa__6383C8BA");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}