// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP_Ticket_ReSell_DAO.Models;

public partial class Transaction
{
    public int ID_Transaction { get; set; }

    public int? ID_Order { get; set; }

    public int? ID_Customer { get; set; }

    public int? ID_Payment { get; set; }

    public DateTime? Created_At { get; set; }

    public string Status { get; set; }

    public decimal? FinalPrice { get; set; }

    public string TransactionCode { get; set; }

    public DateTime? Updated_At { get; set; }

    public virtual Customer ID_CustomerNavigation { get; set; }

    public virtual Order ID_OrderNavigation { get; set; }

    public virtual Payment ID_PaymentNavigation { get; set; }
}